# general configuration
url: http://drupal-mv.de
baseurl: 'drupal-mv.de/'

exclude: [CNAME, Gemfile, LICENSE, README.md]

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/logo.png"
  # author will appear under the avatar (optional)
  author: "DUG MV"
  tagline: "Die Drupal Usergroup für Mecklenburg-Vorpommern"
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true
